# Load environment variables such as OPENAI_API_KEY from the .env file.
from dotenv import load_dotenv

# Import the OpenAI chat model integration for LangChain.
from langchain_openai import ChatOpenAI

# Import message type used to represent user input.
from langchain_core.messages import HumanMessage

# Import the decorator used to convert Python functions into LangChain tools.
from langchain_core.tools import tool

# Import LangGraph components required to build and manage the graph.
from langgraph.graph import START, END, MessagesState, StateGraph

# Import the prebuilt node responsible for executing tool calls.
from langgraph.prebuilt import ToolNode

# Load environment variables from the .env file.
load_dotenv()


# --------------------------------------------------
# 1. Create a tool
# --------------------------------------------------

# Register this Python function as a tool that the LLM can call.
@tool
def multiply(a: int, b: int) -> int:
    """Multiply two integers."""

    # Return the multiplication result to the model.
    return a * b


# Store all tools available to the model in a list.
tools = [multiply]

# --------------------------------------------------
# 2. Create the model and give it access to tools
# --------------------------------------------------

# Initialize the OpenAI chat model used by the agent.
model = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0
)

# Bind the available tools to the model so it can request tool calls.
model_with_tools = model.bind_tools(tools)


# --------------------------------------------------
# 3. Create the agent node
# --------------------------------------------------

# Define the function that runs whenever the "agent" node is executed.
def call_model(state: MessagesState):
    """
    Send the current conversation state to the model.

    The model can either:
    1. Return a normal response.
    2. Request one or more tool calls.
    """

    # Send all messages stored in the graph state to the LLM.
    response = model_with_tools.invoke(state["messages"])

    # Add the model's response back into the graph's message state.
    return {
        "messages": [response]
    }


# --------------------------------------------------
# 4. Decide which node should run next
# --------------------------------------------------

# Define the routing function used after the "agent" node finishes.
def should_continue(state: MessagesState):
    # Get the most recent message generated by the model.
    last_message = state["messages"][-1]

    # Route to the "tools" node if the model requested a tool call.
    if last_message.tool_calls:
        return "tools"

    # End the graph if no tool call is required.
    return END


# --------------------------------------------------
# 5. Build the graph
# --------------------------------------------------

# Create a new graph whose state contains conversation messages.
builder = StateGraph(MessagesState)

# Register "agent" as a graph node that executes call_model().
builder.add_node("agent", call_model)

# Register "tools" as a graph node that executes requested tools.
builder.add_node("tools", ToolNode(tools))

# Set the "agent" node as the first node to run after START.
builder.add_edge(START, "agent")

# Decide where to go after the "agent" node based on should_continue().
builder.add_conditional_edges(
    "agent",
    should_continue,
    {
        # If should_continue() returns "tools", execute the "tools" node.
        "tools": "tools",

        # If should_continue() returns END, terminate the graph.
        END: END,
    },
)

# Return to the "agent" node after a tool finishes executing.
builder.add_edge("tools", "agent")

# --------------------------------------------------
# 6. Compile the graph
# --------------------------------------------------

# Compile the graph into an executable LangGraph application.
agent = builder.compile()

# --------------------------------------------------
# 7. Run the agent
# --------------------------------------------------

# Invoke the graph with the user's initial message.
result = agent.invoke(
    {
        "messages": [
            HumanMessage(
                content="What is 27 multiplied by 14?"
            )
        ]
    }
)

# Print the content of the final message produced by the agent.
print(result["messages"][-1].content)